# Generated by Django 2.1 on 2018-09-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postName', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField()),
                ('dateUpdated', models.DateTimeField()),
                ('filePath', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='blogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read.blogUser'),
        ),
    ]
